EndPoint.WebSite/Models/Checkout/FinalOrderInfo/FinalOrderInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EndPoint.WebSite.Models.Checkout.FinalOrderInfo
{
    public class FinalOrderInfoViewModel
    {
        public int RequestPayId { get; set; }
        public string RefId { get; set; }
        public DateTime FinallyDate { get; set; }
        public decimal PayedAmount { get; set; }
        public List<OrderDetailViewModel> orderDetails { get; set; }
    }

    public class OrderDetailViewModel
    {
        public decimal Price { get; set; }
        public decimal SumPrice { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal PriceWithDiscount { get; set; }
        public string Title { get; set; }
        public int Count { get; set; }
    }
}

EndPoint.WebSite/Models/Checkout/Index/CheckoutViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EndPoint.WebSite.Models.Checkout.Index
{
    public class CheckoutViewModel
    {
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public string PostCode { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public decimal TotalAmount { get; set; }
        public bool agreeToTermsAndConditions { get; set; }

        public List<OrderDetailViewModel> OrderDetails { get; set; }
    }

}

EndPoint.WebSite/Models/Checkout/Index/CheckoutViewModelValidator.cs
using FluentValidation;

namespace EndPoint.WebSite.Models.Checkout.Index
{
    public class CheckoutViewModelValidator : AbstractValidator<CheckoutViewModel>
    {
        public CheckoutViewModelValidator()
        {
            RuleFor(x => x.Address)
                .NotEmpty().WithMessage("آدرس اجباری میباشد")
                .NotNull().WithMessage("آدرس اجباری میباشد");

            RuleFor(x => x.ReceiverName)
                .NotEmpty().WithMessage("نام اجباری میباشد")
                .NotNull().WithMessage("نام اجباری میباشد")
                .MaximumLength(50).WithMessage("نام اجباری بیشتر از 50 کارکتر باشد");

            RuleFor(x => x.ReceiverPhone)
                .NotEmpty().WithMessage("آدرس اجباری میباشد")
                .NotNull().WithMessage("آدرس اجباری میباشد")
                .Matches(@"(\+98|0098|0)?9\d{9}").WithMessage("لطفا شماره تلفن خود را به صورت صحیح وارد نمائید");

            RuleFor(x => x.agreeToTermsAndConditions)
                .Equal(true).WithMessage("برای ثبت نهایی سفارش باید با قوانین و مقررات هگز مارکت موافقت کنید");

            RuleFor(x => x.PostCode)
                .NotEmpty().WithMessage("آدرس اجباری میباشد")
                .NotNull().WithMessage("آدرس اجباری میباشد")
                .Matches(@"\b(?!(\d)\1{3})[13-9]{4}[1346-9][013-9]{5}\b").WithMessage("لطفا کدپستی خود را به صورت صحیح وارد نمائید");

        }
    }

}

EndPoint.WebSite/Models/Checkout/Index/OrderDetailViewModel.cs
namespace EndPoint.WebSite.Models.Checkout.Index
{
    public class OrderDetailViewModel
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public decimal Price { get; set; }
        public decimal SumPrice { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal PriceWithDiscount { get; set; }
        public string Title { get; set; }
        public int Count { get; set; }
    }
}

EndPoint.WebSite/Controllers/CheckoutController.cs
using AutoMapper;
using EndPoint.WebSite.Models.Checkout.Index;
using EndPoint.WebSite.Utilities;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Store_Application.Application.Interfaces.FacadPattern;
using Store_Application.Application.Services.Orders.Commands.EditOrderForSite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EndPoint.WebSite.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly IOrderFacad _orderFacad;
        private readonly ClaimUtility _claimUtility;
        private readonly IMapper _mapper;
        public CheckoutController(IOrderFacad orderFacad, ClaimUtility claimUtility, IMapper mapper)
        {
            _orderFacad = orderFacad;
            _claimUtility = claimUtility;
            _mapper = mapper;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Index()
        {
            var userId = _claimUtility.GetUserId(User);
            var res = _orderFacad.GetOrderForSiteService.Execute(userId);

            if (res.IsSuccess)
            {
                CheckoutViewModel model = _mapper.Map<CheckoutViewModel>(res.Data);

                return View(model);
            }

            return Redirect("/Cart/Index");

        }

        [HttpPost]
        [Authorize]
        public IActionResult Index(CheckoutViewModel req)
        {
            var RequestValidation = new CheckoutViewModelValidator();
            var Validation = RequestValidation.Validate(req);
            Validation.AddToModelState(ModelState, null);

            var userId = _claimUtility.GetUserId(User);

            if (!ModelState.IsValid)
            {
                var model = _orderFacad.GetOrderForSiteService.Execute(userId);

                if (!model.IsSuccess)
                {
                    return Redirect("/Cart");
                }

                req.TotalAmount = model.Data.TotalAmount;
                req.OrderDetails = _mapper.Map<List<OrderDetailViewModel>>(model.Data.OrderDetails);
                
                return View(req);
            }

            var serviceRequest = _mapper.Map<RequestEditOrerForSiteDto>(req);
            serviceRequest.UserId = userId;

            var res = _orderFacad.EditOrderForSiteService.Execute(serviceRequest);

            return RedirectToAction("Index","Pay");

        }

    }
}

EndPoint.WebSite/Views/Checkout/FinalOrderInfo.cshtml
@using Store_Application.Common.Extentions
@using EndPoint.WebSite.Models.Checkout.FinalOrderInfo
@model FinalOrderInfoViewModel
@{
    ViewData["Title"] = "فاکتور سفارش | فروشگاه اینترنتی هگز مارکت";
}
<div class="container-main">
    <div class="d-block">
        <section class="blog-checkout d-block order-1">
            <div class="col-lg">
                <div class="checkout woocommerce-checkout">
                    <div class="content-checkout">
                        <div class="middle-container">
                            <form action="#" class="form-checkout">
                                <div class="col2-set" id="customer-details">
                                    <div class="col-12">
                                        <div class="billing-fields mt-4">
                                            <h4 class="text-success">سفارش دریافت شد</h4>
                                            <p class="thankyou-order-received">
                                                به دلیل ازمایشی بودن سایت درگاه ازمایشی راه اندازی شده است و پرداخت شما به صورت ازمایشی انجام شد
                                                از اینکه من را در تست عملکرد سایت همراهی کردید سپاسگذارم
                                            </p>
                                            <ul class="order-overview">
                                                <li class="order-overview-item">
                                                    کد سفارش :
                                                    <span>DKC-@Model.RequestPayId</span>
                                                </li>
                                                <li class="order-overview-item">
                                                    کد پیگیری سفارش :
                                                    <span>@Model.RefId</span>
                                                </li>
                                                <li class="order-overview-item">
                                                    تاریخ ثبت :
                                                    <span>@Model.FinallyDate.ToShamsi()</span>
                                                </li>
                                                <li class="order-overview-item">
                                                    مبلغ نهایی:
                                                    <span class="amount">
                                                        @Model.PayedAmount.FixedToView()
                                                        <span>تومان</span>
                                                    </span>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <h3 class="order-review-heading">سفارش شما</h3>
                                <div class="checkout-review-order">
                                    <table class="checkout-review-order-table table table-borderless">
                                        <thead>
                                            <tr>
                                                <th scope="col" class="product-name">محصول</th>
                                                <th scope="col" class="product-price">قیمت کل</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @if (Model.orderDetails.Any())
                                            {
                                                foreach (var od in Model.orderDetails)
                                                {
                                                    <tr class="checkout-cart-item">
                                                        <td class="product-name">@od.Title (@od.Count عدد)</td>
                                                        <td class="product-price text-info">
                                                            <span class="amount">
                                                                @((od.PriceWithDiscount * od.Count).FixedToView())
                                                                <span>تومان</span>
                                                            </span>
                                                        </td>
                                                    </tr>
                                                }
                                            }

                                        </tbody>
                                        <tfoot>

                                            <tr class="cart-subtotal">
                                                <th>مجموع</th>
                                                <td>
                                                    <span class="amount">
                                                        @Model.PayedAmount.FixedToView()
                                                        <span>تومان</span>
                                                    </span>
                                                </td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                    <div class="profile-address pr-3 pl-3 mt-5">
                                        <div class="box-header">
                                            <span class="box-title">نشانی ما</span>
                                        </div>
                                        <div class="profile-address-item">
                                            <div class="profile-address-item-top">
                                                <div class="profile-address-item-title">تهران، تهرانسر،‌ تهرانیان</div>
                                            </div>

                                            <div class="profile-address-content">
                                                <ul class="profile-address-info">
                                                    <li>
                                                        <div class="profile-address-info-item location">
                                                            <i class="mdi mdi-map-outline"></i>
                                                            تهران، تهرانسر،‌ تهرانیان
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <div class="profile-address-info-item location">
                                                            <i class="mdi mdi-email-outline"></i>
                                                            Mahdinjf372@gmail.com
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <div class="profile-address-info-item location">
                                                            <i class="mdi mdi-phone"></i>
                                                            09302410082
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <div class="profile-address-info-item location">
                                                            <i class="mdi mdi-account"></i>
                                                            مهدی نجفی پسند
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

EndPoint.WebSite/Views/Checkout/Index.cshtml
@using Store_Application.Common.Extentions
@using EndPoint.WebSite.Models.Checkout.Index
@model CheckoutViewModel
@{
    ViewData["Title"] = "صورتحساب | فروشگاه اینترنتی هگز مارکت";
}
<div class="container-main">
    <div class="d-block">
        <section class="blog-checkout d-block order-1">
            <div class="col-lg">
                <div class="checkout woocommerce-checkout">
                    <div class="content-checkout container">
                        <div class="middle-container">
                            <form asp-controller="Checkout" asp-action="Index" class="form-checkout">
                                <div asp-validation-summary="ModelOnly"></div>
                                <div class="col2-set" id="customer-details">
                                    <div class="col-12">
                                        <div class="billing-fields mt-4">
                                            <h4>جزئیات صورتحساب</h4>
                                            <div class="form-checkout-row">
                                                <div class="validate-required">
                                                    <label for="name">نام تحویل گیرنده <abbr class="required" style="color: red;">*</abbr></label>
                                                    <span asp-validation-for="ReceiverName" class="text text-danger font-small-3"></span>
                                                    <input type="text" id="name" class="input-name-checkout form-control" asp-for="ReceiverName">
                                                </div>

                                                <div class="validate-required">
                                                    <label for="phone-number">شماره موبایل <abbr class="required" style="color: red;">*</abbr></label>
                                                    <span asp-validation-for="ReceiverPhone" class="text text-danger font-small-3"></span>
                                                    <input type="text" id="phone-number" class="input-name-checkout form-control text-left" asp-for="ReceiverPhone">
                                                </div>

                                                <div class="validate-required">
                                                    <label for="post-code">کد پستی <abbr class="required" style="color: red;">*</abbr></label>
                                                    <span asp-validation-for="PostCode" class="text text-danger font-small-3"></span>
                                                    <input type="text" id="post-code" class="input-name-checkout form-control" placeholder="کد پستی را بدون خط تیره بنویسید" asp-for="PostCode">
                                                </div>

                                                <div class="validate-required">
                                                    <label for="address">آدرس <abbr class="required" style="color: red;">*</abbr></label>
                                                    <span asp-validation-for="Address" class="text text-danger font-small-3"></span>
                                                    <input type="text" id="addres" class="input-name-checkout form-control" asp-for="Address">
                                                </div>

                                                <label for="address">
                                                    توضیحات سفارش
                                                    <span class="optional">(اختیاری)</span>
                                                </label>
                                                <textarea asp-for="Description" rows="5" cols="30" id="address" class="textarea-name-checkout form-control" placeholder="یادداشت ها درباره سفارش شما ، برای مثال نکات مهم برای تحویل بار "></textarea>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <h3 class="order-review-heading">سفارش شما</h3>
                                <div class="checkout-review-order">
                                    <table class="checkout-review-order-table table table-borderless">
                                        <thead>
                                            <tr>
                                                <th scope="col" class="product-name">محصول</th>
                                                <th scope="col" class="product-price">قیمت کل</th>
                                            </tr>
                                        </thead>
                                        <tbody class="border-bottom-blue border-bottom-accent-1">
                                            @if (Model.OrderDetails.Any())
                                            {
                                                foreach (var item in Model.OrderDetails)
                                                {
                                                    <tr class="checkout-cart-item">
                                                        <td class="product-name">@item.Title <span class="text text-danger font-small-4">(@item.Count عدد) </span></td>
                                                        <td class="product-price text-info">
                                                            <span class="amount">

                                                                @((item.PriceWithDiscount * item.Count).FixedToView())

                                                                <span>تومان</span>
                                                            </span>
                                                        </td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                        <tfoot>
                                            <tr class="cart-discount">
                                                <th>مبلغ قابل پرداخت</th>
                                                <td data-title=" مبلغ قابل پرداخت ">
                                                    <div class="price">
                                                        <ins>
                                                            <span class="amount">
                                                                @Model.TotalAmount.FixedToView()
                                                                <span>تومان</span>
                                                            </span>
                                                        </ins>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                    <ul class="checkout-payment-methods">

                                        <li class="checkout-payment-method-item d-block">
                                            <label for="#" class="outline-radio">
                                                <input type="radio" name="paymentTypeId" id="paymentType" checked="checked">
                                                <span class="outline-radio-check"></span>
                                            </label>
                                            <label for="paymentType" class="shipping-totals-title-row">
                                                <div class="shipping-totals-title">پرداخت آنلاین</div>
                                            </label>
                                        </li>

                                    </ul>
                                    <div class="form-auth-row">
                                        <label for="#" class="ui-checkbox mt-1">
                                            <input asp-for="agreeToTermsAndConditions" type="checkbox" name="agreeToTermsAndConditions" id="agreeToTermsAndConditions">
                                            <span class="ui-checkbox-check"></span>
                                        </label>
                                        <label for="agreeToTermsAndConditions" class="remember-me mr-0"><a href="#">حریم خصوصی</a> و <a href="#">شرایط قوانین </a>استفاده از سرویس های سایت هگز مارکت را مطالعه نموده و با کلیه موارد آن موافقم <abbr class="required" title="ضروری" style="color:red;">*</abbr></label>
                                        
                                    </div>
                                    <span asp-validation-for="agreeToTermsAndConditions" class="text text-danger font-medium-3 d-block"></span>
                                    <button class="btn-Order btn btn-primary mt-4 mb-3" type="submit">ثبت سفارش</button>

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="~/js/Checkout.js"></script>
}

EndPoint.WebSite/Views/Checkout/_FailedVerificationPayment.cshtml
@{
    Layout = null;
    ViewData["Title"] = "مشکل تایید پرداختن | فروشگاه اینترنتی هگز مارکت";
}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>تایید تراکنش</title>
    <link rel="stylesheet" href="~/css/vendor/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/vendor/materialdesignicons.css">
    <link rel="stylesheet" href="~/css/vendor/bootstrap.css">
    <link rel="stylesheet" href="~/css/vendor/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/vendor/noUISlider.min.css">
    <link rel="stylesheet" href="~/css/main.css">
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-lg">
                <section class="page-account-box">
                    <div class="col-lg-6 col-md-6 col-xs-12 mx-auto">
                        <div class="ds-userlogin">
                            <a href="#" class="account-box-logo">digimarket</a>
                            <div class="account-box">
                                <div class="Login-to-account mt-1">
                                    <div class="account-box-content">
                                        <h4 class="mb-2">تایید پرداخت</h4>
                                        <form action="#" class="form-account text-center">
                                            <div class="user-account-welcome">
                                                <img src="~/images/man.png">
                                            </div>
                                            <div class="made-account">
                                                <h2>پرداخت شما توسط درگاه تایید نشد</h2>
                                                <p>
                                                    لطفا دوباره امتحان کنید
                                                </p>
                                                <p>
                                                    <a href="/Checkout">
                                                        بازگشت به فاکتور
                                                    </a>
                                                </p>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

</body>
<!-- file js---------------------------------------------------->
<script src="~/js/vendor/jquery-3.2.1.min.js"></script>
<script src="~/js/vendor/bootstrap.js"></script>
<!-- plugin----------------------------------------------------->
<script src="~/js/vendor/owl.carousel.min.js"></script>
<script src="~/js/vendor/jquery.countdown.js"></script>
<script src="~/js/vendor/ResizeSensor.min.js"></script>
<script src="~/js/vendor/theia-sticky-sidebar.min.js"></script>
<script src="~/js/vendor/wNumb.js"></script>
<script src="~/js/vendor/nouislider.min.js"></script>
<!-- main js---------------------------------------------------->
<script src="~/js/main.js"></script>
</html>